verbose: true
base_link: base_link
models:
 - name: arm
   type: chain
   frame: base_link
 - name: camera
   type: camera2d
   frame: multisense/left_camera_optical_frame
#free_params:
# - arm_joint_0
error_blocks:
 - name: hand_eye
   type: camera2d_to_arm
   camera: camera
   arm: arm
